package com.r360.coupon_service.exception;

public enum CouponErrors {
    INVALID_CODE, NOT_ACTIVE, EXPIRED, DOMAIN_MISMATCH, MIN_CART,
    LIMIT_EXCEEDED, PAYMENT_NOT_ELIGIBLE, SEGMENT_NOT_ELIGIBLE,
    FRAUD_BLOCKED, IDEMPOTENT_REPLAY, DUPLICATE_ORDER
}